Repository Arique1104/Crate, pull requests merged in 2020-12, with the labels that each got.

#44 Products table
  code/api/src/config/config.json
  code/api/src/migrations/20201207225501-modify_products_add_style.js
  code/api/src/seeders/2-products.js
Labels: BEE 🐝, priority: 1 🚨

#47 Adds primary style key and secondary style key to user table.
  code/api/src/migrations/20201208215930-modify_users_add_primary_style.js
  code/api/src/migrations/20201208220512-modify_users_add_secondary_style.js
  code/api/src/seeders/1-user.js
Labels: BEE 🐝, priority: 1 🚨

#59 Reducer tests: crate and crates
  code/web/package-lock.json
  code/web/package.json
  code/web/src/__mocks__/axios.js
  code/web/src/modules/crate/List.js
  code/web/src/modules/crate/List.test.js
  code/web/src/modules/crate/api/state.test.js
Labels: FEE 💸, priority: 1 🚨, type: documentation 📓, type: test 🔮, ❔ question❔

#56 Seeds
  code/api/public/images/stock/survey/survey-classicaccessory-female.jpg
  code/api/public/images/stock/survey/survey-classicaccessory-male.jpg
  code/api/public/images/stock/survey/survey-classicbottom.png
  code/api/public/images/stock/survey/survey-classicshoes.jpeg
  code/api/public/images/stock/survey/survey-classictop.jpg
  code/api/public/images/stock/survey/survey-classicunderpants-female.jpg
  code/api/public/images/stock/survey/survey-classicunderpants-male.jpg
  code/api/public/images/stock/survey/survey-punkbottom.jpg
  code/api/public/images/stock/survey/survey-punkshoes.jpg
  code/api/public/images/stock/survey/survey-punktop-male.jpg
  code/api/public/images/stock/survey/survey-punktop.png
  code/api/public/images/stock/survey/survey-sportyaccessory-female.jpg
  code/api/public/images/stock/survey/survey-sportyaccessory-male.jpg
  code/api/public/images/stock/survey/survey-sportybottom.jpg
  code/api/public/images/stock/survey/survey-sportyshoes.jpeg
  code/api/public/images/stock/survey/survey-sportytop-male.jpg
  code/api/public/images/stock/survey/survey-sportytop.jpg
  code/api/src/config/params.json
  code/api/src/modules/user/resolvers.js
  code/api/src/seeders/2-products.js
  code/web/public/images/stock/survey/survey-classicbottom.png
  code/web/public/images/stock/survey/survey-classicshoes.jpeg
  code/web/public/images/stock/survey/survey-classictop.jpg
  code/web/public/images/stock/survey/survey-punkbottoms.jpg
  code/web/public/images/stock/survey/survey-punkshoes.jpg
  code/web/public/images/stock/survey/survey-punktop.png
  code/web/public/images/stock/survey/survey-sportybottoms.jpg
  code/web/public/images/stock/survey/survey-sportyshoe.jpeg
  code/web/public/images/stock/survey/survey-sportytop.jpg
  code/web/src/modules/crate/Item.js
  code/web/src/modules/survey/StyleSurvey.js
  code/web/src/modules/survey/api/actions.js
  code/web/src/modules/survey/api/state.js
  code/web/src/setup/routes/index.js
  code/web/src/setup/routes/survey.js
Labels: BEE 🐝, BEEFEE 🐮, FEE 💸, priority: 1 🚨

#67 Style form functionality
  code/web/.github/pull_request_template.md
  code/web/package.json
  code/web/src/modules/crate/api/actions.js
  code/web/src/modules/survey/StyleSurvey.js
  code/web/src/setup/store.js
Labels: FEE 💸, priority: 1 🚨, type: enhancement 🌟

#68 Survey actions
  code/api/package-lock.json
  code/api/package.json
  code/web/src/modules/api/actions.js
  code/web/src/modules/api/state.js
  code/web/src/modules/crate/api/state.js
  code/web/src/modules/survey/StyleSurvey.js
  code/web/src/modules/survey/api/actions.js
  code/web/src/modules/survey/api/state.js
  code/web/src/setup/store.js
Labels: BEEFEE 🐮

#69 Readme
  README.md
Labels: BEEFEE 🐮, priority: 2 🔨, type: documentation 📓

#73 Drew READme
  README.md
Labels: type: documentation 📓

#74 Needed tests
  code/web/src/modules/crate/Item.test.js
  code/web/src/modules/survey/StyleSurvey.test.js
  code/web/src/modules/survey/api/actions.js
  code/web/src/modules/survey/api/state.js
  code/web/src/modules/survey/api/state.test.js
Labels: FEE 💸, type: test 🔮
